//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int id { get; set; }
        public Nullable<int> RenterCount { get; set; }
        public Nullable<int> TenantCount { get; set; }
        public Nullable<int> PropertyCount { get; set; }
        public Nullable<int> PropertiesSold { get; set; }
    }
}
