//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Details
    {
        public int Request_Id { get; set; }
        public int Property_id { get; set; }
        public int Seller_Id { get; set; }
        public int Customer_id { get; set; }
    
        public virtual Prop Prop { get; set; }
        public virtual Renter Renter { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
