//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sold_Property
    {
        public int Sold_id { get; set; }
        public int property_id { get; set; }
        public int seller_id { get; set; }
        public int customer_id { get; set; }
        public int deposit_amount { get; set; }
        public int rent { get; set; }
        public string date_of_sale { get; set; }
    
        public virtual Prop Prop { get; set; }
        public virtual Renter Renter { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
